### PR TITLE
Add ts type definitions

### PR DESCRIPTION
**Pull request by mattphillips**
### What

Add type definitions for core Jest matchers and jest-extended matchers to return the matcher object

### Why

#4 

### Notes

I'm not convinced by this change and would like help investigating if we can dynamically re-assign all properties of an interface to a new return type. 

That way all other definitions we just work out of the box and the types won't need to be managed by hand with every change in core/jest-extended

### CODE REVIEW

**Comment by fgkramer** [comment]
Hi,
Is there something I can do to help getting this merged?

**Comment by mattphillips** [comment]
@fgkramer @natealcedo @byCedric

I've now played with TS a bit and think I may have just cracked this problem without the need for hand crafted types!

Would you be able to look at the PR and maybe even pull it down and link it to a project (`yarn link`) and see if this solves the problem? Cheers

**Comment by mattphillips** [comment]
In fact I've just `yarn link`ed it locally and seems to be working - I'll go ahead and merge/publish this :)

**Comment by fgkramer** [comment]
Amazing, thank you :)

**Pull request merged**
