### PR TITLE
throw error if it isn't a match error

### PR DESCRIPTION
**Pull request by tonivj5**
### What
Simply throw error if it isn't a match error

### Why
https://github.com/mattphillips/jest-chain/issues/22

### Housekeeping

- [ ] Unit tests
- [ ] Documentation is up to date
- [ ] No additional lint warnings

### CODE REVIEW

**Comment by tonivj5** [comment]
I will add tests if there's intention to merge it :sweat_smile:

**Comment by abhijit945** [comment]
Can we merge this?

**Comment by MatthewPardini** [comment]
Is this repo dead? Why is this not actively being looked at. It is a huge blocker to using jest-chain

**Comment by mattphillips** [comment]
Sorry for the delay in coming to this!! This issue has now actually been fixed in: https://www.npmjs.com/package/jest-chain/v/1.1.6

**Pull request closed without merging**
