### PR TITLE
Update to be compatible with latest @types/jest

### PR DESCRIPTION
**Pull request by dobesv**
Note that this change is not backward-compatible, this will not work with older versions of @types/jest.

### CODE REVIEW

**Comment by dobesv** [comment]
@Userbit cool, thanks!

**Comment by mattphillips** [comment]
Hey @dobesv @Userbit thanks for the PR/review!

I'm not sure this PR should be necessary as the types in `@types/jest` have been updated to be backwards compatible (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41766).

I've just started a new project locally with `jest-chain` and the latest `@types/jest` types and it all worked fine.

I'm going to go ahead and close this for now, but please feel free to re-open and let me know if it still isn't working.

**Comment by dobesv** [comment]
That sounds even better.

**Comment by ben-tbotlabs** [comment]
Unfortunately this does not work with the "not" matcher, and possibly others.

Using
@types/jest@25.1.0
jest@25.1.0
jest-chain@1.1.4
jest-extended@0.11.5
ts-jest@25.0.0

Results in 

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/index.spec.ts:10:5 - error TS2339: Property 'not' does not exist on type 'ChainedMatchers<string>'.

    10                  .not.toBeNil()

for the .spec.ts file below

function hello() {
	return 'world';
}

describe( 'hello-world', () => {

	it( 'hello invalid', async () => {
		const v = hello();
		expect( v )
			.not.toBeNil()
			.toHaveLength( 5 );

	} );

	it( 'hello valid', async () => {
		const v = hello();
		expect( v )
			.toBeString()
			.toHaveLength( 5 );
	} );
} );

**Comment by dobesv** [comment]
Oh yeah, they did rearrange things a bit in `@jest/types`, didn't they.  I remember running into that, I had to use a different base type.

**Comment by ben-tbotlabs** [comment]
I made a Stackblitz project to reproduce the problem quickly https://stackblitz.com/edit/typescript-c4nmax

Error in Stackblitz:
You will see the error squiggly in index.spec.ts

Locally:
Download from Stackblitz
npm install
npm test

**Comment by mattphillips** [comment]
Just published https://www.npmjs.com/package/jest-chain/v/1.1.5 with @dobesv's fix.

Hope you don't mind @dobesv that I copied the solution from this PR and didn't merge, I didn't fancy dealing with the merge conflicts in package.json/yarn.lock

**Comment by dobesv** [comment]
No problem, thanks!

**Pull request closed without merging**
